name: Build-2

on:
  push:
    branches: [ main ]

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: maven

      - name: Version
        id: vars
        shell: bash
        run: |
          cd helloworld-java-bin
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT

  release:
    needs: [ precheck ]
    if: endsWith('${{ needs.precheck.outputs.version }}', '-SNAPSHOT') 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: maven

      - name: Build
        run: |
          cd helloworld-java-bin
          ./mvnw -ntp -B --file pom.xml verify
